name: quill_zefyr_bijection
description: Converts QuillJs JSON to Zefyr Compatible JSON Delta
version: 0.0.1
author: Suraj Elapully
homepage: https://github.com/essuraj/Quill-Zefyr-Bijection

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  quill_delta: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

