name: quill_zefyr_bijection
description: Converts Quill.Js JSON to Zefyr Compatible JSON Delta fo user with Zefyr editor flutter package.
version: 0.2.1
homepage: https://github.com/essuraj/Quill-Zefyr-Bijection

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  quill_delta: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
